GET http://localhost:3001/ping
Content-Type: text/plain

###

POST http://localhost:3001/api/users
Content-Type: application/json
Accept: application/json

{
    "username": "test",
    "password": "password",
    "name": "Test User"
}

###

POST http://localhost:3001/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username" : "test",
  "password" : "password"
}

###

GET http://localhost:3001/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 4416544d-096d-4095-b07e-750941d1ae8b

###

PATCH http://localhost:3001/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 4416544d-096d-4095-b07e-750941d1ae8b

{
  "name" : "Bambang"
}

###

DELETE http://localhost:3001/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: 4416544d-096d-4095-b07e-750941d1ae8b

###

POST http://localhost:3001/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 4416544d-096d-4095-b07e-750941d1ae8b

{
  "first_name" : "Joko",
  "last_name" : "Morro",
  "email" : "joko@pzn.com",
  "phone" : "324234234234"
}


###

GET http://localhost:3001/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 4416544d-096d-4095-b07e-750941d1ae8b

###

GET http://localhost:3001/api/contacts/475
Content-Type: application/json
Accept: application/json
Authorization: 4416544d-096d-4095-b07e-750941d1ae8b

### Update

PUT http://localhost:3001/api/contacts/475
Content-Type: application/json
Accept: application/json
Authorization: 4416544d-096d-4095-b07e-750941d1ae8b

{
  "first_name": "Rully",
  "last_name": "Nugraha",
  "email": "rully@pzn.com",
  "phone": "324234234234"
}

### Delete Contact

DELETE http://localhost:3001/api/contacts/475
Content-Type: application/json
Accept: application/json
Authorization: 4416544d-096d-4095-b07e-750941d1ae8b

### Create Address

POST http://localhost:3001/api/contacts/476/addresses
Content-Type: application/json
Accept: application/json
Authorization: 4416544d-096d-4095-b07e-750941d1ae8b

{
  "street" : "Kantor",
  "city" : "Jakarta",
  "province" : "DKI JAKARTA",
  "country" : "Indonesia",
  "postal_code" : "324234"
}


### List Addresses

GET http://localhost:3001/api/contacts/476/addresses
Content-Type: application/json
Accept: application/json
Authorization: 4416544d-096d-4095-b07e-750941d1ae8b


### Get Address

GET http://localhost:3001/api/contacts/476/addresses/78
Content-Type: application/json
Accept: application/json
Authorization: 4416544d-096d-4095-b07e-750941d1ae8b

### Update Address

PUT http://localhost:3001/api/contacts/476/addresses/78
Content-Type: application/json
Accept: application/json
Authorization: 4416544d-096d-4095-b07e-750941d1ae8b

{
  "street" : "Kantor Bekerja",
  "city" : "Bekasi",
  "province" : "Jawa Barat",
  "country" : "Indonesia",
  "postal_code" : "324234"
}

### Remove Address

DELETE http://localhost:3001/api/contacts/476/addresses/78
Content-Type: application/json
Accept: application/json
Authorization: 4416544d-096d-4095-b07e-750941d1ae8b
